(vector) @keyword
(wallet) @keyword
(bind) @function
(certify) @keyword
(transfer) @keyword
(drain) @keyword
(project) @keyword
(reconstruct) @keyword
(query) @keyword
(record) @keyword
(contract) @keyword
(action) @keyword
(ctx) @function
(type_tag) @type
(identifier) @variable
(integer) @number
(string) @string
(comment) @comment
