/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_vector = 2,
  anon_sym_COLON = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_wallet = 6,
  anon_sym_bind = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_certify = 10,
  anon_sym_with = 11,
  anon_sym_transfer = 12,
  anon_sym_to = 13,
  anon_sym_amount = 14,
  anon_sym_drain = 15,
  anon_sym_by = 16,
  anon_sym_project = 17,
  anon_sym_into = 18,
  anon_sym_reconstruct = 19,
  anon_sym_from = 20,
  anon_sym_query = 21,
  anon_sym_record = 22,
  anon_sym_contract = 23,
  anon_sym_LBRACE = 24,
  anon_sym_RBRACE = 25,
  anon_sym_action = 26,
  anon_sym_COMMA = 27,
  anon_sym_policy = 28,
  anon_sym_ctx = 29,
  anon_sym_position = 30,
  anon_sym_free = 31,
  anon_sym_bound = 32,
  anon_sym_unit = 33,
  anon_sym_zero = 34,
  anon_sym_spatial = 35,
  anon_sym_DOT = 36,
  sym_comment = 37,
  sym_integer = 38,
  sym_string = 39,
  sym_source_file = 40,
  sym_statement = 41,
  sym_vector_decl = 42,
  sym_wallet_decl = 43,
  sym_certify_stmt = 44,
  sym_transfer_stmt = 45,
  sym_drain_stmt = 46,
  sym_project_stmt = 47,
  sym_reconstruct_stmt = 48,
  sym_query_stmt = 49,
  sym_record_stmt = 50,
  sym_contract_decl = 51,
  sym_contract_action = 52,
  sym_action_args = 53,
  sym_named_argument_list = 54,
  sym_named_argument = 55,
  sym_drain_clause = 56,
  sym_policy_clause = 57,
  sym_context_expr = 58,
  sym_type_tag = 59,
  sym_vector_literal = 60,
  sym_integer_list = 61,
  sym_expression = 62,
  sym_path = 63,
  sym_call = 64,
  sym_scalar = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_contract_decl_repeat1 = 67,
  aux_sym_named_argument_list_repeat1 = 68,
  aux_sym_integer_list_repeat1 = 69,
  aux_sym_path_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_vector] = "vector",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_wallet] = "wallet",
  [anon_sym_bind] = "bind",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_certify] = "certify",
  [anon_sym_with] = "with",
  [anon_sym_transfer] = "transfer",
  [anon_sym_to] = "to",
  [anon_sym_amount] = "amount",
  [anon_sym_drain] = "drain",
  [anon_sym_by] = "by",
  [anon_sym_project] = "project",
  [anon_sym_into] = "into",
  [anon_sym_reconstruct] = "reconstruct",
  [anon_sym_from] = "from",
  [anon_sym_query] = "query",
  [anon_sym_record] = "record",
  [anon_sym_contract] = "contract",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_action] = "action",
  [anon_sym_COMMA] = ",",
  [anon_sym_policy] = "policy",
  [anon_sym_ctx] = "ctx",
  [anon_sym_position] = "position",
  [anon_sym_free] = "free",
  [anon_sym_bound] = "bound",
  [anon_sym_unit] = "unit",
  [anon_sym_zero] = "zero",
  [anon_sym_spatial] = "spatial",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_vector_decl] = "vector_decl",
  [sym_wallet_decl] = "wallet_decl",
  [sym_certify_stmt] = "certify_stmt",
  [sym_transfer_stmt] = "transfer_stmt",
  [sym_drain_stmt] = "drain_stmt",
  [sym_project_stmt] = "project_stmt",
  [sym_reconstruct_stmt] = "reconstruct_stmt",
  [sym_query_stmt] = "query_stmt",
  [sym_record_stmt] = "record_stmt",
  [sym_contract_decl] = "contract_decl",
  [sym_contract_action] = "contract_action",
  [sym_action_args] = "action_args",
  [sym_named_argument_list] = "named_argument_list",
  [sym_named_argument] = "named_argument",
  [sym_drain_clause] = "drain_clause",
  [sym_policy_clause] = "policy_clause",
  [sym_context_expr] = "context_expr",
  [sym_type_tag] = "type_tag",
  [sym_vector_literal] = "vector_literal",
  [sym_integer_list] = "integer_list",
  [sym_expression] = "expression",
  [sym_path] = "path",
  [sym_call] = "call",
  [sym_scalar] = "scalar",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_contract_decl_repeat1] = "contract_decl_repeat1",
  [aux_sym_named_argument_list_repeat1] = "named_argument_list_repeat1",
  [aux_sym_integer_list_repeat1] = "integer_list_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_vector] = anon_sym_vector,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_wallet] = anon_sym_wallet,
  [anon_sym_bind] = anon_sym_bind,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_certify] = anon_sym_certify,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_transfer] = anon_sym_transfer,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_amount] = anon_sym_amount,
  [anon_sym_drain] = anon_sym_drain,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_project] = anon_sym_project,
  [anon_sym_into] = anon_sym_into,
  [anon_sym_reconstruct] = anon_sym_reconstruct,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_contract] = anon_sym_contract,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_policy] = anon_sym_policy,
  [anon_sym_ctx] = anon_sym_ctx,
  [anon_sym_position] = anon_sym_position,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_bound] = anon_sym_bound,
  [anon_sym_unit] = anon_sym_unit,
  [anon_sym_zero] = anon_sym_zero,
  [anon_sym_spatial] = anon_sym_spatial,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_vector_decl] = sym_vector_decl,
  [sym_wallet_decl] = sym_wallet_decl,
  [sym_certify_stmt] = sym_certify_stmt,
  [sym_transfer_stmt] = sym_transfer_stmt,
  [sym_drain_stmt] = sym_drain_stmt,
  [sym_project_stmt] = sym_project_stmt,
  [sym_reconstruct_stmt] = sym_reconstruct_stmt,
  [sym_query_stmt] = sym_query_stmt,
  [sym_record_stmt] = sym_record_stmt,
  [sym_contract_decl] = sym_contract_decl,
  [sym_contract_action] = sym_contract_action,
  [sym_action_args] = sym_action_args,
  [sym_named_argument_list] = sym_named_argument_list,
  [sym_named_argument] = sym_named_argument,
  [sym_drain_clause] = sym_drain_clause,
  [sym_policy_clause] = sym_policy_clause,
  [sym_context_expr] = sym_context_expr,
  [sym_type_tag] = sym_type_tag,
  [sym_vector_literal] = sym_vector_literal,
  [sym_integer_list] = sym_integer_list,
  [sym_expression] = sym_expression,
  [sym_path] = sym_path,
  [sym_call] = sym_call,
  [sym_scalar] = sym_scalar,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_contract_decl_repeat1] = aux_sym_contract_decl_repeat1,
  [aux_sym_named_argument_list_repeat1] = aux_sym_named_argument_list_repeat1,
  [aux_sym_integer_list_repeat1] = aux_sym_integer_list_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_vector] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wallet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bind] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_certify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_transfer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_amount] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_drain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_project] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_into] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reconstruct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_policy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ctx] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_position] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bound] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_zero] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spatial] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_vector_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_wallet_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_certify_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_transfer_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_drain_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_project_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_reconstruct_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_query_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_record_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_contract_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_contract_action] = {
    .visible = true,
    .named = true,
  },
  [sym_action_args] = {
    .visible = true,
    .named = true,
  },
  [sym_named_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_named_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_drain_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_policy_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_context_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_type_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_vector_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_contract_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_named_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '#', 14,
        '(', 8,
        ')', 9,
        ',', 12,
        '.', 13,
        '/', 2,
        ':', 5,
        ';', 7,
        '=', 6,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0xfeff) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'i', 6,
        'p', 7,
        'q', 8,
        'r', 9,
        's', 10,
        't', 11,
        'u', 12,
        'v', 13,
        'w', 14,
        'z', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xa0 ||
          lookahead == 0xfeff) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(16);
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(22);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(27);
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_by);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'x') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(64);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_ctx);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 48:
      if (lookahead == 'm') ADVANCE(70);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 52:
      if (lookahead == 'j') ADVANCE(74);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'h') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(85);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_bind);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(86);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(87);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_into);
      END_STATE();
    case 72:
      if (lookahead == 'c') ADVANCE(90);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 75:
      if (lookahead == 'y') ADVANCE(93);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(94);
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_unit);
      END_STATE();
    case 80:
      if (lookahead == 'o') ADVANCE(98);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_zero);
      END_STATE();
    case 84:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_bound);
      END_STATE();
    case 87:
      if (lookahead == 'f') ADVANCE(102);
      END_STATE();
    case 88:
      if (lookahead == 'a') ADVANCE(103);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_drain);
      END_STATE();
    case 90:
      if (lookahead == 'y') ADVANCE(104);
      END_STATE();
    case 91:
      if (lookahead == 'i') ADVANCE(105);
      END_STATE();
    case 92:
      if (lookahead == 'c') ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 94:
      if (lookahead == 's') ADVANCE(107);
      END_STATE();
    case 95:
      if (lookahead == 'd') ADVANCE(108);
      END_STATE();
    case 96:
      if (lookahead == 'a') ADVANCE(109);
      END_STATE();
    case 97:
      if (lookahead == 'f') ADVANCE(110);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(111);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_amount);
      END_STATE();
    case 102:
      if (lookahead == 'y') ADVANCE(113);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(114);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_policy);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(115);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 109:
      if (lookahead == 'l') ADVANCE(118);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_vector);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_wallet);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_certify);
      END_STATE();
    case 114:
      if (lookahead == 't') ADVANCE(120);
      END_STATE();
    case 115:
      if (lookahead == 'n') ADVANCE(121);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_project);
      END_STATE();
    case 117:
      if (lookahead == 'r') ADVANCE(122);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_spatial);
      END_STATE();
    case 119:
      if (lookahead == 'r') ADVANCE(123);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_contract);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_position);
      END_STATE();
    case 122:
      if (lookahead == 'u') ADVANCE(124);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_transfer);
      END_STATE();
    case 124:
      if (lookahead == 'c') ADVANCE(125);
      END_STATE();
    case 125:
      if (lookahead == 't') ADVANCE(126);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_reconstruct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_vector] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_wallet] = ACTIONS(1),
    [anon_sym_bind] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_certify] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_transfer] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_amount] = ACTIONS(1),
    [anon_sym_drain] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_project] = ACTIONS(1),
    [anon_sym_into] = ACTIONS(1),
    [anon_sym_reconstruct] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_contract] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_policy] = ACTIONS(1),
    [anon_sym_ctx] = ACTIONS(1),
    [anon_sym_position] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_bound] = ACTIONS(1),
    [anon_sym_unit] = ACTIONS(1),
    [anon_sym_zero] = ACTIONS(1),
    [anon_sym_spatial] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(75),
    [sym_statement] = STATE(2),
    [sym_vector_decl] = STATE(6),
    [sym_wallet_decl] = STATE(6),
    [sym_certify_stmt] = STATE(6),
    [sym_transfer_stmt] = STATE(6),
    [sym_drain_stmt] = STATE(6),
    [sym_project_stmt] = STATE(6),
    [sym_reconstruct_stmt] = STATE(6),
    [sym_query_stmt] = STATE(6),
    [sym_record_stmt] = STATE(6),
    [sym_contract_decl] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_vector] = ACTIONS(7),
    [anon_sym_wallet] = ACTIONS(9),
    [anon_sym_certify] = ACTIONS(11),
    [anon_sym_transfer] = ACTIONS(13),
    [anon_sym_drain] = ACTIONS(15),
    [anon_sym_project] = ACTIONS(17),
    [anon_sym_reconstruct] = ACTIONS(19),
    [anon_sym_query] = ACTIONS(21),
    [anon_sym_record] = ACTIONS(23),
    [anon_sym_contract] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_vector,
    ACTIONS(9), 1,
      anon_sym_wallet,
    ACTIONS(11), 1,
      anon_sym_certify,
    ACTIONS(13), 1,
      anon_sym_transfer,
    ACTIONS(15), 1,
      anon_sym_drain,
    ACTIONS(17), 1,
      anon_sym_project,
    ACTIONS(19), 1,
      anon_sym_reconstruct,
    ACTIONS(21), 1,
      anon_sym_query,
    ACTIONS(23), 1,
      anon_sym_record,
    ACTIONS(25), 1,
      anon_sym_contract,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(6), 10,
      sym_vector_decl,
      sym_wallet_decl,
      sym_certify_stmt,
      sym_transfer_stmt,
      sym_drain_stmt,
      sym_project_stmt,
      sym_reconstruct_stmt,
      sym_query_stmt,
      sym_record_stmt,
      sym_contract_decl,
  [53] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_vector,
    ACTIONS(34), 1,
      anon_sym_wallet,
    ACTIONS(37), 1,
      anon_sym_certify,
    ACTIONS(40), 1,
      anon_sym_transfer,
    ACTIONS(43), 1,
      anon_sym_drain,
    ACTIONS(46), 1,
      anon_sym_project,
    ACTIONS(49), 1,
      anon_sym_reconstruct,
    ACTIONS(52), 1,
      anon_sym_query,
    ACTIONS(55), 1,
      anon_sym_record,
    ACTIONS(58), 1,
      anon_sym_contract,
    STATE(3), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(6), 10,
      sym_vector_decl,
      sym_wallet_decl,
      sym_certify_stmt,
      sym_transfer_stmt,
      sym_drain_stmt,
      sym_project_stmt,
      sym_reconstruct_stmt,
      sym_query_stmt,
      sym_record_stmt,
      sym_contract_decl,
  [106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [259] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [310] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 11,
      ts_builtin_sym_end,
      anon_sym_vector,
      anon_sym_wallet,
      anon_sym_certify,
      anon_sym_transfer,
      anon_sym_drain,
      anon_sym_project,
      anon_sym_reconstruct,
      anon_sym_query,
      anon_sym_record,
      anon_sym_contract,
  [361] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_named_argument,
    STATE(58), 1,
      sym_expression,
    STATE(82), 1,
      sym_named_argument_list,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [391] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_named_argument,
    STATE(58), 1,
      sym_expression,
    STATE(115), 1,
      sym_named_argument_list,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [421] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_named_argument,
    STATE(58), 1,
      sym_expression,
    STATE(105), 1,
      sym_named_argument_list,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [451] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_path_repeat1,
    ACTIONS(103), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [471] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym_expression,
    STATE(61), 1,
      sym_named_argument,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [495] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(50), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [516] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_DOT,
    STATE(32), 1,
      aux_sym_path_repeat1,
    ACTIONS(111), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [533] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(92), 1,
      sym_type_tag,
    ACTIONS(113), 6,
      anon_sym_position,
      anon_sym_free,
      anon_sym_bound,
      anon_sym_unit,
      anon_sym_zero,
      anon_sym_spatial,
  [548] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(41), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [569] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(100), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [590] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(106), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [611] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(65), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [632] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(74), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [653] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_DOT,
    STATE(32), 1,
      aux_sym_path_repeat1,
    ACTIONS(115), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [670] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(57), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [691] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(112), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [712] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(117), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_integer,
      sym_string,
    STATE(42), 2,
      sym_path,
      sym_call,
  [733] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_DOT,
    ACTIONS(120), 1,
      anon_sym_EQ,
    STATE(25), 1,
      aux_sym_path_repeat1,
    ACTIONS(103), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
      anon_sym_DOT,
  [765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [787] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [798] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_SEMI,
    ACTIONS(130), 1,
      anon_sym_drain,
    ACTIONS(132), 1,
      anon_sym_policy,
    STATE(54), 1,
      sym_drain_clause,
    STATE(101), 1,
      sym_policy_clause,
  [817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_drain,
      anon_sym_COMMA,
      anon_sym_policy,
  [828] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_action,
    STATE(43), 2,
      sym_contract_action,
      aux_sym_contract_decl_repeat1,
  [842] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 1,
      anon_sym_action,
    STATE(45), 2,
      sym_contract_action,
      aux_sym_contract_decl_repeat1,
  [856] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_action,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(43), 2,
      sym_contract_action,
      aux_sym_contract_decl_repeat1,
  [870] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym_scalar,
    ACTIONS(145), 3,
      sym_identifier,
      sym_integer,
      sym_string,
  [882] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      aux_sym_named_argument_list_repeat1,
  [895] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    STATE(120), 1,
      sym_action_args,
  [908] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
    ACTIONS(157), 1,
      sym_integer,
    STATE(93), 1,
      sym_integer_list,
  [921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_policy,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(103), 1,
      sym_policy_clause,
  [934] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_integer_list_repeat1,
  [947] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_named_argument_list_repeat1,
  [960] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_integer_list_repeat1,
  [973] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_policy,
    ACTIONS(169), 1,
      anon_sym_SEMI,
    STATE(114), 1,
      sym_policy_clause,
  [986] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      aux_sym_named_argument_list_repeat1,
  [999] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_integer_list_repeat1,
  [1012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      anon_sym_SEMI,
      anon_sym_policy,
  [1020] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1028] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    STATE(78), 1,
      sym_vector_literal,
  [1038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_ctx,
    STATE(98), 1,
      sym_context_expr,
  [1048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 2,
      anon_sym_RBRACE,
      anon_sym_action,
  [1064] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      anon_sym_action,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1080] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1088] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_EQ,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_bind,
  [1109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
  [1116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
  [1123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_identifier,
  [1130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
  [1144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [1158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
  [1165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_identifier,
  [1172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_SEMI,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_SEMI,
  [1200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_identifier,
  [1214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COLON,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_from,
  [1228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_EQ,
  [1242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
  [1249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [1256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
  [1263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_SEMI,
  [1270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_EQ,
  [1277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
  [1284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
  [1291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_SEMI,
  [1298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_SEMI,
  [1305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_SEMI,
  [1319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_amount,
  [1326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_SEMI,
  [1333] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_SEMI,
  [1340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_amount,
  [1347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_SEMI,
  [1354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SEMI,
  [1361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
  [1368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_SEMI,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_integer,
  [1382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_SEMI,
  [1389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SEMI,
  [1396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_with,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_to,
  [1410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_SEMI,
  [1417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_by,
  [1424] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_SEMI,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_SEMI,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_SEMI,
  [1452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_into,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
  [1466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 106,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 157,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 191,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 225,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 259,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 293,
  [SMALL_STATE(16)] = 310,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 344,
  [SMALL_STATE(19)] = 361,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 421,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 471,
  [SMALL_STATE(24)] = 495,
  [SMALL_STATE(25)] = 516,
  [SMALL_STATE(26)] = 533,
  [SMALL_STATE(27)] = 548,
  [SMALL_STATE(28)] = 569,
  [SMALL_STATE(29)] = 590,
  [SMALL_STATE(30)] = 611,
  [SMALL_STATE(31)] = 632,
  [SMALL_STATE(32)] = 653,
  [SMALL_STATE(33)] = 670,
  [SMALL_STATE(34)] = 691,
  [SMALL_STATE(35)] = 712,
  [SMALL_STATE(36)] = 733,
  [SMALL_STATE(37)] = 753,
  [SMALL_STATE(38)] = 765,
  [SMALL_STATE(39)] = 776,
  [SMALL_STATE(40)] = 787,
  [SMALL_STATE(41)] = 798,
  [SMALL_STATE(42)] = 817,
  [SMALL_STATE(43)] = 828,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 856,
  [SMALL_STATE(46)] = 870,
  [SMALL_STATE(47)] = 882,
  [SMALL_STATE(48)] = 895,
  [SMALL_STATE(49)] = 908,
  [SMALL_STATE(50)] = 921,
  [SMALL_STATE(51)] = 934,
  [SMALL_STATE(52)] = 947,
  [SMALL_STATE(53)] = 960,
  [SMALL_STATE(54)] = 973,
  [SMALL_STATE(55)] = 986,
  [SMALL_STATE(56)] = 999,
  [SMALL_STATE(57)] = 1012,
  [SMALL_STATE(58)] = 1020,
  [SMALL_STATE(59)] = 1028,
  [SMALL_STATE(60)] = 1038,
  [SMALL_STATE(61)] = 1048,
  [SMALL_STATE(62)] = 1056,
  [SMALL_STATE(63)] = 1064,
  [SMALL_STATE(64)] = 1072,
  [SMALL_STATE(65)] = 1080,
  [SMALL_STATE(66)] = 1088,
  [SMALL_STATE(67)] = 1095,
  [SMALL_STATE(68)] = 1102,
  [SMALL_STATE(69)] = 1109,
  [SMALL_STATE(70)] = 1116,
  [SMALL_STATE(71)] = 1123,
  [SMALL_STATE(72)] = 1130,
  [SMALL_STATE(73)] = 1137,
  [SMALL_STATE(74)] = 1144,
  [SMALL_STATE(75)] = 1151,
  [SMALL_STATE(76)] = 1158,
  [SMALL_STATE(77)] = 1165,
  [SMALL_STATE(78)] = 1172,
  [SMALL_STATE(79)] = 1179,
  [SMALL_STATE(80)] = 1186,
  [SMALL_STATE(81)] = 1193,
  [SMALL_STATE(82)] = 1200,
  [SMALL_STATE(83)] = 1207,
  [SMALL_STATE(84)] = 1214,
  [SMALL_STATE(85)] = 1221,
  [SMALL_STATE(86)] = 1228,
  [SMALL_STATE(87)] = 1235,
  [SMALL_STATE(88)] = 1242,
  [SMALL_STATE(89)] = 1249,
  [SMALL_STATE(90)] = 1256,
  [SMALL_STATE(91)] = 1263,
  [SMALL_STATE(92)] = 1270,
  [SMALL_STATE(93)] = 1277,
  [SMALL_STATE(94)] = 1284,
  [SMALL_STATE(95)] = 1291,
  [SMALL_STATE(96)] = 1298,
  [SMALL_STATE(97)] = 1305,
  [SMALL_STATE(98)] = 1312,
  [SMALL_STATE(99)] = 1319,
  [SMALL_STATE(100)] = 1326,
  [SMALL_STATE(101)] = 1333,
  [SMALL_STATE(102)] = 1340,
  [SMALL_STATE(103)] = 1347,
  [SMALL_STATE(104)] = 1354,
  [SMALL_STATE(105)] = 1361,
  [SMALL_STATE(106)] = 1368,
  [SMALL_STATE(107)] = 1375,
  [SMALL_STATE(108)] = 1382,
  [SMALL_STATE(109)] = 1389,
  [SMALL_STATE(110)] = 1396,
  [SMALL_STATE(111)] = 1403,
  [SMALL_STATE(112)] = 1410,
  [SMALL_STATE(113)] = 1417,
  [SMALL_STATE(114)] = 1424,
  [SMALL_STATE(115)] = 1431,
  [SMALL_STATE(116)] = 1438,
  [SMALL_STATE(117)] = 1445,
  [SMALL_STATE(118)] = 1452,
  [SMALL_STATE(119)] = 1459,
  [SMALL_STATE(120)] = 1466,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_stmt, 7, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_stmt, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_decl, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drain_stmt, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_stmt, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_certify_stmt, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reconstruct_stmt, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transfer_stmt, 8, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_decl, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_stmt, 8, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_decl, 7, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transfer_stmt, 7, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wallet_decl, 8, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transfer_stmt, 9, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contract_decl_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument_list, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_list, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument_list, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_list, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_named_argument_list_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_named_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_list_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_integer_list_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drain_clause, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_action, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_action, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_tag, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_expr, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_literal, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_expr, 4, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_args, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_literal, 3, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_policy_clause, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_args, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
